cafe/urls.py
from django.urls import path

from . import views
app_name = 'cafe'

urlpatterns = [
    # path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('reservation/', views.reservation, name='reservation'),
    path('special_dishes/', views.special_dishes, name='special_dishes'),
    path('team/', views.team, name='team'),
    path('menu/', views.menu, name='menu'),
    path('', views.home, name='home'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cafe.urls', namespace='cafe')),
]


urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cafe/models.py
from distutils.command.upload import upload
from email import message
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models
from django.utils.timezone import datetime, now

# Create your models here.
import datetime

from django.db.models.fields.related import ForeignKey

def increment_booking_number():
  last_booking = Order.objects.all().order_by('id').last()
  if not last_booking:
    return str(datetime.date.today().year) + str(datetime.date.today().month).zfill(2) + '0000'
  oid = last_booking.oid
  booking_int = int(oid[9:13])
  new_booking_int = booking_int + 1
  new_oid =  str(str(datetime.date.today().year)) + str(datetime.date.today().month).zfill(2) + str(new_booking_int).zfill(4)
  return new_oid

class Order(models.Model):
    oid = models.CharField(max_length = 20, default = increment_booking_number, editable=False)
    # oitem = models.ManyToManyField(to='Item')
    customer = ForeignKey('Customer',on_delete=models.CASCADE, default='')
    worker = ForeignKey('Worker',on_delete=models.CASCADE, default='', blank=True, null=True)
#     odate = models.DateField( blank=True, default=datetime.datetime.now().date())
    odate = models.DateField( blank=True, auto_now=False,auto_now_add=False, )
#     otime = models.TimeField( blank=True, default=datetime.datetime.now().time())
    otime = models.TimeField( blank=True, auto_now=False,auto_now_add=False)
    iotem = models.ManyToManyField(to='Item')
    status_list = [
      ('queued','queued'),
      ('serving', 'serving'),
      ('ready', 'ready')
    ]
    status = models.CharField(max_length=10,default='queued', choices=status_list)
 
    total_price = models.FloatField(default=0)
    
    def __str__(self):
        return self.customer.fname + ' ' + self.oid
def image_upload(instance, filename):
      imagenaeme , extention = filename.split(".")
      return "Items/%s.%s"%( instance.id, extention)

def worker_image_upload(instance, filename):
      imagenaeme , extention = filename.split(".")
      return "Worker/%s.%s"%( instance.ssn, extention)

class Item(models.Model):
      title = models.CharField(default='', max_length=15)
      ingredients = models.TextField(default='', max_length=1000)
      price = models.IntegerField(default=0)
      image = models.ImageField(upload_to=image_upload, default='')
#       status_list = [
#       ('Breakfast','Breakfast'),
#       ('Lunch', 'Lunch'),
#       ('Dinner', 'Dinner')
#     ]
#       status = models.CharField(max_length=10,default='Breakfast', choices=status_list)
      # imenu= models.ManyToManyField(to='Menu', blank=True)
      def __str__(self):
            return self.title

class Menu(models.Model):
      title = models.CharField(max_length=50, default='')
      mitem = models.ManyToManyField(to=Item)
      code_list = [
      ('Breakfast','Breakfast'),
      ('Lunch', 'Lunch'),
      ('Dinner', 'Dinner')
    ]
      code = models.CharField(max_length=10,default='Breakfast', choices=code_list)
      # imenu= models.ManyToManyField(to='Menu', blank=True)
      # mmanager = models.ForeignKey('Manager',on_delete=models.DO_NOTHING, default='')
      
      def __str__(self):
            return self.title

class Person(models.Model):
      ssn = models.CharField(primary_key=True, default='', max_length=10)
      fname = models.CharField( max_length=50,default='')
      lname = models.CharField( max_length=50, default='')
      address = models.CharField( max_length=100, default='')
      telephone = models.CharField( max_length=10, default='')
      def __str__(self):
            return self.fname +'_' + self.lname +'_' + self.ssn
          
class Worker(Person):
      salary = models.FloatField(default=1500)
      image = models.ImageField(upload_to=worker_image_upload, default='')
# class Manager(Person):
#       pass
      # dob = models.DateField()
      
      
class Customer(models.Model):
      fname = models.CharField( max_length=50,default='')
      lname = models.CharField( max_length=50, default='')
      address = models.CharField( max_length=100, default='', blank=True)
      telephone = models.CharField( max_length=10, default='')
      email = models.EmailField(max_length=254,blank=True, null=True) #null=True Django will store empty values as NULL in the database , blank=True the field is allowed to be blank
      def __str__(self):
            return self.fname +'_' + self.lname +'_' + self.telephone



class Reserve(models.Model):
      name = models.CharField(max_length = 100,default='')
      email = models.EmailField(max_length=150,default='')
      message = models.TextField(max_length=500, default='')
      date = models.DateField( auto_now=False, auto_now_add=False)
      time = models.TimeField(auto_now=False, auto_now_add=False)
      
      nperson = models.IntegerField( default=1)
      def __str__(self):
            return self.name

cafe/views.py
from multiprocessing import context
from tkinter import Menu
from django.shortcuts import render

from .form import ApplyForm

from .models import Item,Menu,Order,Customer,Worker,Person
# Create your views here.


def about(request):
    return render(request,"cafe/about.html")
def home(request):
    return render(request,"cafe/home.html")
def reservation(request):
    
    if request.method == 'POST':
        form = ApplyForm(request.POST)
        if form.is_valid():
            myform = form.save()
    else:
        form = ApplyForm()

    context = {'form': form}

    return render(request,"cafe/reservation.html",context)
def team(request):
    workers = Worker.objects.all()
    context={
        'workers': workers
    }
    return render(request,"cafe/team.html", context)


def special_dishes(request):
    return render(request,"cafe/special-dishes.html")


def menu(request):
    # items = Item.objects.all()
    # menus = Menu.objects.search(code='Breakfast')
    
    menus = Menu.objects.all()
    context={
    'menus': menus
    }
    
    return render(request,"cafe/menu.html",context)

cafe/templates/cafe/about.html
{% extends 'base.html' %}
{% block body %}
  

{% load static %}

  


	<!-- Welcome Section -->
<section id="gtco-welcome" class="bg-white section-padding">
    <div class="container">
        <div class="section-content">
            <div class="row">
                <div class="col-sm-5 img-bg d-flex shadow align-items-center justify-content-center justify-content-md-end img-2" style="background-image: url({% static 'img/hero-2.jpg' %});">
                    
                </div>
                <div class="col-sm-7 py-5 pl-md-0 pl-4">
                    <div class="heading-section pl-lg-5 ml-md-5">
                        <span class="subheading">
                            About
                        </span>
                        <h2>
                            Welcome to Resto
                        </h2>
                    </div>
                    <div class="pl-lg-5 ml-md-5">
                        <p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                        <h3 class="mt-5">Special Recipe</h3>
                        <div class="row">
                            <div class="col-4">
                                <a href="#" class="thumb-menu">
                                    <img class="img-fluid img-cover" src="{% static 'img/hero-1.jpg' %}" />
                                    <h6>Australian Organic Beef</h6>
                                </a>
                            </div>
                            <div class="col-4">
                                <a href="#" class="thumb-menu">
                                    <img class="img-fluid img-cover" src="{% static 'img/hero-1.jpg' %}" />
                                    <h6>Australian Organic Beef</h6>
                                </a>
                            </div>
                            <div class="col-4">
                                <a href="#" class="thumb-menu">
                                    <img class="img-fluid img-cover" src="{% static 'img/hero-1.jpg' %}"/>
                                    <h6>Australian Organic Beef</h6>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End of Welcome Section -->		

	
</div>


{% endblock body %}

cafe/templates/cafe/index.html
<!DOCTYPE html>
<!--
	Resto by GetTemplates.co
	URL: https://gettemplates.co
-->
<html lang="en">
{% load static %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Resto - Restaurant Bootstrap 4 Template by GetTemplates.co</title>
    <meta name="description" content="Resto">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/select2/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/owlcarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'https://cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/brands.css' %}">

    <!-- Fonts -->
    <link rel="stylesheet"
          href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,700|Josefin+Sans:300,400,700' %}">
    <link rel="stylesheet" href="{% static 'https://cdn.linearicons.com/free/1.0.0/icon-font.min.css' %}">
    <link rel="stylesheet" href="{% static 'https://use.fontawesome.com/releases/v5.8.1/css/all.css' %}"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">

    <!-- Modernizr JS for IE8 support of HTML5 elements and media queries -->
    <script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js' %}"></script>

</head>

{{{% block content %}
  
{% endblock content %}}}


<!-- External JS -->
<script src="{% static 'https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js' %}"></script>
<script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/select2/select2.min.js ' %}"></script>
<script src="{% static 'vendor/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'https://cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.min.js' %}"></script>
<script src="{% static 'vendor/stellar/jquery.stellar.js' %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js' %}"></script>

<!-- Main JS -->
<script src="{% static 'js/app.min.js ' %}"></script>
</body>
</html>

cafe/templates/cafe/menu.html
 {% extends 'base.html' %} {% block body %} {% load static %}

        <!-- Menu Section -->
        <section id="gtco-menu" class="section-padding">
            <div class="container">
                <div class="section-content">
                    <div class="row mb-5">
                        <div class="col-md-12">
                            <div class="heading-section text-center">
                                <span class="subheading">
                            Specialties
                        </span>
                                <h2>
                                    Our Menu
                                </h2>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4 menu-wrap">
                            <div class="heading-menu">
                                <h3 class="text-center mb-5">Breakfast</h3>
                            </div>
                            {% for menu in menus %} {% if menu.code == "Breakfast" %} {% for item in menu.mitem.all %}

                            <div class="menus d-flex align-items-center">
                                <div class="menu-img rounded-circle">
                                    <img class="img-fluid" src='{{item.image.url}}' alt="">
                                </div>
                                <div class="text-wrap">
                                    <div class="row align-items-start">
                                        <div class="col-8">
                                            <h4>{{item}}</h4>
                                        </div>
                                        <div class="col-4">
                                            <h4 class="text-muted menu-price">${{item.price}}</h4>
                                        </div>
                                    </div>
                                    <p>{{item.ingredients}}</p>
                                </div>
                            </div>

                            {% endfor %} {% endif %}{% endfor %}


                        </div>

                        <div class="col-lg-4 menu-wrap">
                            <div class="heading-menu">
                                <h3 class="text-center mb-5">Lunch</h3>
                            </div>
                            {% for menu in menus %} {% if menu.code == "Lunch" %} {% for item in menu.mitem.all %}

                            <div class="menus d-flex align-items-center">
                                <div class="menu-img rounded-circle">
                                    <img class="img-fluid" src='{{item.image.url}}' alt="">
                                </div>
                                <div class="text-wrap">
                                    <div class="row align-items-start">
                                        <div class="col-8">
                                            <h4>{{item}}</h4>
                                        </div>
                                        <div class="col-4">
                                            <h4 class="text-muted menu-price">${{item.price}}</h4>
                                        </div>
                                    </div>
                                    <p>{{item.ingredients}}</p>
                                </div>
                            </div>

                            {% endfor %} {% endif %}{% endfor %}


                        </div>
                        <div class="col-lg-4 menu-wrap">
                            <div class="heading-menu">
                                <h3 class="text-center mb-5">Dinner</h3>
                            </div>
                            {% for menu in menus %} {% if menu.code == "Dinner" %} {% for item in menu.mitem.all %}

                            <div class="menus d-flex align-items-center">
                                <div class="menu-img rounded-circle">
                                    <img class="img-fluid" src='{{item.image.url}}' alt="">
                                </div>
                                <div class="text-wrap">
                                    <div class="row align-items-start">
                                        <div class="col-8">
                                            <h4>{{item}}</h4>
                                        </div>
                                        <div class="col-4">
                                            <h4 class="text-muted menu-price">${{item.price}}</h4>
                                        </div>
                                    </div>
                                    <p>{{item.ingredients}}</p>
                                </div>
                            </div>

                            {% endfor %} {% endif %}{% endfor %}


                        </div>

                    </div>
                </div>
            </div>
        </section>
        <!-- End of menu Section -->

    {% endblock body %}

cafe/templates/cafe/reservation.html
{% extends 'base.html' %}
{% block body %}
  

{% load static %}

{% load bootstrap4 %}
{% bootstrap_javascript jquery='full' %}



{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{{ form.media }}

		<!-- Reservation Section -->
{% comment %} <section id="gtco-reservation" class="bg-fixed bg-white section-padding overlay" style="background-image: url({% static 'img/reservation-bg.jpg'%});"> {% endcomment %}
<section id="gtco-reservation" class="bg-fixed bg-white" >
    <div class="container">

        
        <div class="row">
            <div class="col-lg-12">
                <div class="section-content bg-white p-3 shadow">
                    <div class="heading-section text-center">
                        <span class="subheading">
                            Reservation
                        </span>
                        <h2>
                            Book Now
                        </h2>
                    
                    <form method="post" name="contact-us" action="" class="form">
                       

                        </div> 
                        {% csrf_token %}

                        {% bootstrap_form form %}
                   
                             <button class="btn btn-primary btn-shadow btn-lg" type="submit" name="submit">Make reservation</button>
                          
 
                       
                    </form>
                </div>
            </div>
        </div>
        
   </div>
</section>
<!-- End of Reservation Section -->	
<br>
<br>
<br>

</div>



</div>
{% endblock body %}

templates/base.html
<!DOCTYPE html>
<!--
	Resto by GetTemplates.co
	URL: https://gettemplates.co
-->
<html lang="en">
{% load static %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Resto - Restaurant Bootstrap 4 Template by GetTemplates.co</title>
    <meta name="description" content="Resto">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/select2/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/owlcarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet"
          href="https://cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/brands.css">

    <!-- Fonts -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700|Josefin+Sans:300,400,700">
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">

    <!-- Modernizr JS for IE8 support of HTML5 elements and media queries -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"></script>

</head>

<body data-spy="scroll" data-target="#navbar">
      <div id="side-nav" class="sidenav">
          <a href="{% static 'javascript:void(0)' %}" id="side-nav-close">&times;</a>
  
          <div class="sidenav-content">
              <p>
                  Kuncen WB1, Wirobrajan 10010, DIY
              </p>
              <p>
                  <span class="fs-16 primary-color">(+68) 120034509</span>
              </p>
              <p>info@yourdomain.com</p>
          </div>
      </div>
      <div id="side-search" class="sidenav">
          <a href="{% static 'javascript:void(0)' %}" id="side-search-close">&times;</a>
          <div class="sidenav-content">
              <form action="">
  
                  <div class="input-group md-form form-sm form-2 pl-0">
                      <input class="form-control my-0 py-1 red-border" type="text" placeholder="Search" aria-label="Search">
                      <div class="input-group-append">
                          <button class="input-group-text red lighten-3" id="basic-text1">
                              <i class="fas fa-search text-grey" aria-hidden="true"></i>
                        </button>
                      </div>
                  </div>
  
              </form>
          </div>
  
  
      </div>
      <div id="canvas-overlay"></div>
      <div class="boxed-page">
          <nav id="navbar-header" class="navbar navbar-expand-lg">
              <div class="container">
                  <a class="navbar-brand navbar-brand-center d-flex align-items-center p-0 only-mobile" href="/">
                      <img src="{% static 'img/logo.png' %}" alt="">
                  </a>
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="lnr lnr-menu"></span>
          </button>
  
                  <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
                      <ul class="navbar-nav d-flex justify-content-between">
                          <li class="nav-item only-desktop">
                              <a class="nav-link" id="side-nav-open" href="#">
                                  <span class="lnr lnr-menu"></span>
                              </a>
                          </li>
                          <div class="d-flex flex-lg-row flex-column">
                              <li class="nav-item active">
                                  <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link" href="{% url 'cafe:about' %}">About</a>
                              </li>
  
                              <li class="nav-item dropdown">
                                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Special Dishes
                          </a>
                                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                      <a class="dropdown-item" href="../special_dishes">Beef Steak Sauce</a>
                                      <a class="dropdown-item" href="../special_dishes">Salmon Zucchini</a>
                                  </div>
                              </li>
                          </div>
                      </ul>
  
                      <a class="navbar-brand navbar-brand-center d-flex align-items-center only-desktop" href="#">
                          <img src="{% static 'img/logo.png' %}" alt="">
                      </a>
                      <ul class="navbar-nav d-flex justify-content-between">
                          <div class="d-flex flex-lg-row flex-column">
                              <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'cafe:menu' %}">Menu</a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link" href="{% url 'cafe:team' %}">Team</a>
                              </li>
  
                              <li class="nav-item dropdown">
                                  <a class="nav-link" href="{% url 'cafe:reservation' %}">Reservation</a>
                              </li>
                          </div>
                          <li class="nav-item">
                              <a id="side-search-open" class="nav-link" href="#">
                                  <span class="lnr lnr-magnifier"></span>
                              </a>
                          </li>
                      </ul>
                  </div>
              </div>
          </nav>

{% block body %}
  
{% endblock body %}

<footer class="mastfoot pb-5 bg-white section-padding pb-0">
      <div class="inner container">
          <div class="row">
              <div class="col-lg-4">
                  <div class="footer-widget pr-lg-5 pr-0">
                      <img src="{% static 'img/logo.png' %}" class="img-fluid footer-logo mb-3" alt="">
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et obcaecati quisquam id sit omnis
                          explicabo voluptate aut placeat, soluta, nisi ea magni facere, itaque incidunt modi? Magni,
                          et voluptatum dolorem.</p>
                      <nav class="nav nav-mastfoot justify-content-start">
                          <a class="nav-link" href="#">
                              <i class="fab fa-facebook-f"></i>
                          </a>
                          <a class="nav-link" href="#">
                              <i class="fab fa-twitter"></i>
                          </a>
                          <a class="nav-link" href="#">
                              <i class="fab fa-instagram"></i>
                          </a>
                      </nav>
                  </div>

              </div>
              <div class="col-lg-4">
                  <div class="footer-widget px-lg-5 px-0">
                      <h4>Open Hours</h4>
                      <ul class="list-unstyled open-hours">
                          <li class="d-flex justify-content-between"><span>Monday</span><span>9:00 - 24:00</span></li>
                          <li class="d-flex justify-content-between"><span>Tuesday</span><span>9:00 - 24:00</span>
                          </li>
                          <li class="d-flex justify-content-between"><span>Wednesday</span><span>9:00 - 24:00</span>
                          </li>
                          <li class="d-flex justify-content-between"><span>Thursday</span><span>9:00 - 24:00</span>
                          </li>
                          <li class="d-flex justify-content-between"><span>Friday</span><span>9:00 - 02:00</span></li>
                          <li class="d-flex justify-content-between"><span>Saturday</span><span>9:00 - 02:00</span>
                          </li>
                          <li class="d-flex justify-content-between"><span>Sunday</span><span> Closed</span></li>
                      </ul>
                  </div>

              </div>

              <div class="col-lg-4">
                  <div class="footer-widget pl-lg-5 pl-0">
                      <h4>Newsletter</h4>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                      <form id="newsletter">
                          <div class="form-group">
                              <input type="email" class="form-control" id="emailNewsletter"
                                     aria-describedby="emailNewsletter" placeholder="Enter email">
                          </div>
                          <button type="submit" class="btn btn-primary w-100">Submit</button>
                      </form>
                  </div>

              </div>
              <div class="col-md-12 d-flex align-items-center">
                  <p class="mx-auto text-center mb-0">Copyright 2019. All Right Reserved. Design by <a
                          href="{% static 'https://gettemplates.co' %}" target="_blank">GetTemplates</a></p>
              </div>

          </div>
      </div>
  </footer>
</div>
</div>
<!-- External JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/select2/select2.min.js ' %}"></script>
<script src="{% static 'vendor/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="https://cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.min.js"></script>
<script src="{% static 'vendor/stellar/jquery.stellar.js' %}" type="text/javascript" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>

<!-- Main JS -->
<script src="{% static 'js/app.min.js ' %}"></script>
</body>
</html>